In [73]:
from pytrends.request import TrendReq
import pandas as pd
import matplotlib.pyplot as plt

In [74]:
pytrends = TrendReq(hl='en-US', tz=360)

In [75]:
kw_list = ["Medicare", 'Crime', 'Immigration', 'Unemployment', 'Social Security']
pytrends.build_payload(kw_list, cat=0, timeframe='now 7-d', geo = 'US-MN', gprop='')

In [76]:
topics = pytrends.interest_by_region(resolution='CITY', inc_geo_code=False, inc_low_vol=True)
topics.head(20)

,Medicare,Crime,Immigration,Unemployment,Social Security
geoName,,,,,
Duluth MN-Superior WI,21,14,5,30,30
Fargo-Valley City ND,19,15,2,36,28
La Crosse-Eau Claire WI,18,18,7,29,28
Mankato MN,17,20,6,28,29
Minneapolis-St. Paul MN,26,16,6,23,29
Rochester MN-Mason City IA-Austin MN,31,14,4,21,30

In [77]:
topics = pytrends.interest_over_time()
topics.head(20)

,Medicare,Crime,Immigration,Unemployment,Social Security,isPartial
date,,,,,,
2019-12-01 19:00:00,15,7,2,4,6,False
2019-12-01 20:00:00,9,6,2,3,7,False
2019-12-01 21:00:00,6,7,2,4,7,False
2019-12-01 22:00:00,6,7,2,3,6,False
2019-12-01 23:00:00,6,7,3,4,6,False
2019-12-02 00:00:00,5,7,2,4,6,False
2019-12-02 01:00:00,5,5,2,3,6,False
2019-12-02 02:00:00,4,7,2,2,6,False
2019-12-02 03:00:00,4,7,3,3,7,False
2019-12-02 04:00:00,2,9,3,3,8,False
2019-12-02 05:00:00,3,9,4,3,6,False
2019-12-02 06:00:00,6,10,3,5,7,False
2019-12-02 07:00:00,2,7,2,4,9,False
2019-12-02 08:00:00,3,13,6,3,8,False
2019-12-02 09:00:00,3,14,1,6,3,False
2019-12-02 10:00:00,4,13,2,5,10,False
2019-12-02 11:00:00,2,8,2,22,12,False
2019-12-02 12:00:00,6,5,1,100,10,False
2019-12-02 13:00:00,8,4,3,67,12,False
2019-12-02 14:00:00,11,5,2,60,16,False

In [78]:
kw_list = ["Terrorism", 'Homelessness', 'Gun control', 'Military Budget', 'Climate Change']
pytrends.build_payload(kw_list, cat=0, timeframe='now 7-d', geo = 'US-MN', gprop='')

In [79]:
topics = pytrends.interest_by_region(resolution='CITY', inc_geo_code=False, inc_low_vol=True)
topics.head(20)

,Terrorism,Homelessness,Gun control,Military Budget,Climate Change
geoName,,,,,
Duluth MN-Superior WI,8,6,13,0,73
Fargo-Valley City ND,11,7,15,0,67
La Crosse-Eau Claire WI,9,12,12,0,67
Mankato MN,20,0,10,0,70
Minneapolis-St. Paul MN,8,12,16,1,63
Rochester MN-Mason City IA-Austin MN,7,14,18,0,61

In [80]:
topics = pytrends.interest_over_time()
topics.head(20)

,Terrorism,Homelessness,Gun control,Military Budget,Climate Change,isPartial
date,,,,,,
2019-12-01 19:00:00,6,6,8,0,24,False
2019-12-01 20:00:00,8,2,7,2,26,False
2019-12-01 21:00:00,6,2,4,2,23,False
2019-12-01 22:00:00,3,9,11,2,32,False
2019-12-01 23:00:00,3,3,6,0,28,False
2019-12-02 00:00:00,16,9,14,0,33,False
2019-12-02 01:00:00,5,24,3,3,41,False
2019-12-02 02:00:00,13,1,12,0,47,False
2019-12-02 03:00:00,10,5,10,3,49,False
2019-12-02 04:00:00,9,9,10,2,51,False
2019-12-02 05:00:00,14,3,3,0,64,False
2019-12-02 06:00:00,0,5,15,0,41,False
2019-12-02 07:00:00,18,9,9,0,26,False
2019-12-02 08:00:00,39,13,0,26,38,False
2019-12-02 09:00:00,0,0,46,0,16,False
2019-12-02 10:00:00,14,0,14,0,42,False
2019-12-02 11:00:00,0,0,0,0,17,False
2019-12-02 12:00:00,0,0,13,0,18,False
2019-12-02 13:00:00,5,11,16,0,24,False
2019-12-02 14:00:00,5,10,13,0,44,False